<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="projetLong" nsURI="http://www.example.org/projetLong" nsPrefix="projetLong">
  <eClassifiers xsi:type="ecore:EClass" name="outil">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" lowerBound="1"
        upperBound="-1" eType="#//Table" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cols" lowerBound="2" upperBound="-1"
        eType="#//Colonne" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Colonne" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColIdent" eSuperTypes="#//Colonne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="idents" lowerBound="1"
        upperBound="-1" eType="#//IdentValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColDev" instanceTypeName="Script" eSuperTypes="#//Colonne">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scripte" lowerBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColSimple" eSuperTypes="#//Colonne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" lowerBound="1"
        upperBound="-1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="val" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColRef" eSuperTypes="#//Colonne">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Data" lowerBound="1" eType="#//Colonne"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tableref" lowerBound="1"
        eType="#//Table"/>
  </eClassifiers>
</ecore:EPackage>
